stages:
  - smoke
  - regress
  - report

default:
  image: maven:3.9.9-eclipse-temurin-17
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .m2/repository
  artifacts:
    when: always
    paths:
      - target/site/allure-maven-plugin

smoke-job:
  stage: smoke
  tags:
    - shhopat-runner
  script:
    - mvn clean test -Dgroups=smoke

regress-job:
  stage: regress
  tags:
    - shhopat-runner
  script:
    - mvn clean test -Dgroups=regress

allure-report:
  stage: report
  tags:
    - shhopat-runner
  script:
    - mvn allure:report
